# Generated by Django 5.2.8 on 2025-12-19 09:37

import uuid_utils.compat
from django.db import migrations, models



def resource_mapping(apps, schema_editor):
    # 本地精简内核：不执行基于 workflow/flow 的历史资源映射回填
    return


class Migration(migrations.Migration):
    dependencies = [
        ('system_manage', '0004_alter_systemsetting_type_and_more'),
        ('knowledge', '0007_remove_knowledgeworkflowversion_workflow_and_more'),
        ('application', '0003_application_stt_model_params_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMapping',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id',
                 models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False,
                                  verbose_name='主键id')),
                ('source_type', models.CharField(
                    choices=[('KNOWLEDGE', '知识库'), ('APPLICATION', '应用'), ('TOOL', '工具'), ('MODEL', '模型')],
                    db_index=True, verbose_name='关联资源类型')),
                ('target_type', models.CharField(
                    choices=[('KNOWLEDGE', '知识库'), ('APPLICATION', '应用'), ('TOOL', '工具'), ('MODEL', '模型')],
                    db_index=True, verbose_name='被关联资源类型')),
                ('source_id', models.CharField(db_index=True, max_length=128, verbose_name='关联资源id')),
                ('target_id', models.CharField(db_index=True, max_length=128, verbose_name='被关联资源id')),
            ],
            options={
                'db_table': 'resource_mapping',
            },
        ),
        migrations.RunPython(resource_mapping, atomic=False)
    ]
