# Generated by Django 5.2.16 on 2026-08-17 13:05

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0005_resourcemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceOffboard',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('offboarded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('exported_path', models.CharField(blank=True, default='', max_length=1024)),
                ('counts', models.JSONField(default=dict)),
                ('force', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workspace_offboard',
            },
        ),
    ]
