# Generated by Django 5.2.16 on 2026-08-18

import uuid_utils.compat
import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("system_manage", "0006_workspaceoffboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceoffboard",
            name="storage_cleanup_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspaceoffboard",
            name="storage_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workspaceoffboard",
            name="storage_last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspaceoffboard",
            name="storage_status",
            field=models.CharField(
                choices=[("COMPLETED", "Completed"), ("STORAGE_PENDING", "Storage pending")],
                default="COMPLETED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceOffboardStorageCleanup",
            fields=[
                ("id", models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=2048)),
                ("status", models.CharField(
                    choices=[("COMPLETED", "Completed"), ("STORAGE_PENDING", "Storage pending")],
                    default="STORAGE_PENDING",
                    max_length=20,
                )),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("workspace_offboard", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="storage_cleanup_objects",
                    to="system_manage.workspaceoffboard",
                )),
            ],
            options={"db_table": "workspace_offboard_storage_cleanup"},
        ),
        migrations.AddConstraint(
            model_name="workspaceoffboardstoragecleanup",
            constraint=models.UniqueConstraint(
                fields=("workspace_offboard", "key"), name="workspace_offboard_storage_key"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceoffboardstoragecleanup",
            index=models.Index(
                fields=["workspace_offboard", "status"], name="workspace_offboard_storage_st"
            ),
        ),
    ]
