# Generated by Django 5.2.16 on 2026-08-18

from django.db import migrations


def backfill_legacy_storage_failures(apps, schema_editor):
    workspace_model = apps.get_model("system_manage", "WorkspaceOffboard")
    cleanup_model = apps.get_model("system_manage", "WorkspaceOffboardStorageCleanup")
    pending = "STORAGE_PENDING"
    for tombstone in workspace_model.objects.all().iterator():
        failures = (tombstone.counts or {}).get("storage_cleanup_errors") or []
        valid_failures = [item for item in failures if isinstance(item, dict) and item.get("key")]
        if not valid_failures:
            continue
        for item in valid_failures:
            attempts = item.get("attempts")
            if not isinstance(attempts, int) or attempts < 1:
                attempts = 1
            cleanup_model.objects.get_or_create(
                workspace_offboard_id=tombstone.id,
                key=str(item["key"]),
                defaults={
                    "status": pending,
                    "attempts": attempts,
                    "last_error": str(item.get("error") or "legacy storage cleanup failed"),
                    "last_error_at": tombstone.offboarded_at,
                },
            )
        latest = valid_failures[-1]
        tombstone.storage_status = pending
        tombstone.storage_cleanup_attempts = max(tombstone.storage_cleanup_attempts, 1)
        tombstone.storage_last_error = str(latest.get("error") or "legacy storage cleanup failed")
        tombstone.storage_last_error_at = tombstone.offboarded_at
        tombstone.save(
            update_fields=[
                "storage_status",
                "storage_cleanup_attempts",
                "storage_last_error",
                "storage_last_error_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [("system_manage", "0007_workspaceoffboard_storage")]

    operations = [migrations.RunPython(backfill_legacy_storage_failures, migrations.RunPython.noop)]
