# Generated by Django 5.2.16 on 2026-08-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_publicfileaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeAction',
        ),
    ]
