"""add assignments

Revision ID: 10421097d4d1
Revises: bec3fa5d16c7
Create Date: 2026-08-09 00:32:32.576883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10421097d4d1'
down_revision: Union[str, Sequence[str], None] = 'bec3fa5d16c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending_screen', 'screen_passed', 'interviewing', 'offer', 'hired', 'offer_rejected', 'rejected', 'closed_after_hire', 'closed_by_job', name='assignment_status'), nullable=False),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('close_reason', sa.String(length=256), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_assignments_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assignments_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_assignments_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_assignments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index(op.f('ix_assignments_candidate_id'), 'assignments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assignments_job_id'), 'assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_workspace_id'), 'assignments', ['workspace_id'], unique=False)
    op.create_index('uq_assignments_idem', 'assignments', ['workspace_id', 'idempotency_key'], unique=True)
    op.create_index('uq_assignments_pair', 'assignments', ['candidate_id', 'job_id'], unique=True)
    op.add_column('jobs', sa.Column('hc_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('jobs', sa.Column('hc_filled', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'hc_filled')
    op.drop_column('jobs', 'hc_reserved')
    op.drop_index('uq_assignments_pair', table_name='assignments')
    op.drop_index('uq_assignments_idem', table_name='assignments')
    op.drop_index(op.f('ix_assignments_workspace_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_job_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_candidate_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS assignment_status")
