"""add resume pipeline tables

Revision ID: 3fc5f2ab57e8
Revises: 4426ee145861
Create Date: 2026-08-08 02:18:17.232295

"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fc5f2ab57e8'
down_revision: str | Sequence[str] | None = '4426ee145861'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_mappings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('pii_type', sa.Enum('phone', 'email', 'id_card', 'name', 'address', name='pii_type'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=False),
    sa.Column('ir_locator', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pii_mappings'))
    )
    op.create_table('resume_irs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('valid_chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_resume_irs'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('revision_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_events_event_id')),
    comment='不可变审计事件：只 append，无 update/delete 路径'
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', 'purged', 'pending_review', name='candidate_status'), nullable=False),
    sa.Column('deleted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('email_enc', sa.Text(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('latest_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_candidates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index('ix_candidates_dedup', 'candidates', ['workspace_id', 'name', 'phone_hash', 'email_hash'], unique=False, postgresql_where=sa.text("status IN ('active','deleted','pending_review')"))
    op.create_index('ix_candidates_search_tsv', 'candidates', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_index(op.f('ix_candidates_workspace_id'), 'candidates', ['workspace_id'], unique=False)
    op.create_index('ix_candidates_workspace_status', 'candidates', ['workspace_id', 'status'], unique=False)
    op.create_table('parse_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=True),
    sa.Column('referrer', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'failed', 'dead_letter', name='parse_run_status'), nullable=False),
    sa.Column('failure_class', sa.Enum('not_retryable', 'retryable', name='failure_class'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ir_hash', sa.String(length=64), nullable=True),
    sa.Column('candidate_hash', sa.String(length=64), nullable=True),
    sa.Column('profile_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_parse_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_runs'))
    )
    op.create_index(op.f('ix_parse_runs_run_id'), 'parse_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_parse_runs_status'), 'parse_runs', ['status'], unique=False)
    op.create_index(op.f('ix_parse_runs_workspace_id'), 'parse_runs', ['workspace_id'], unique=False)
    op.create_table('candidate_embeddings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.Enum('summary', 'education', 'work', 'project', 'skills', name='embedding_segment'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_embeddings_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_embeddings'))
    )
    op.create_index('ix_candidate_embeddings_hnsw', 'candidate_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('candidate_overrides',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('action', sa.Enum('override', 'clear', name='override_action'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_candidate_overrides_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_overrides_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_overrides'))
    )
    op.create_index(op.f('ix_candidate_overrides_candidate_id'), 'candidate_overrides', ['candidate_id'], unique=False)
    op.create_table('candidate_revisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_revisions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_revisions')),
    sa.UniqueConstraint('revision_id', name=op.f('uq_candidate_revisions_revision_id'))
    )
    op.create_index(op.f('ix_candidate_revisions_candidate_id'), 'candidate_revisions', ['candidate_id'], unique=False)
    op.create_table('resume_files',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_resume_files_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_files'))
    )
    # ### end Alembic commands ###

    # 全文索引维护：search_text 写入时同步 search_tsv（否则 GIN 索引检索不到）
    op.execute("""
    CREATE FUNCTION candidates_search_tsvector_sync() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
      NEW.search_tsv := to_tsvector('simple', coalesce(NEW.search_text, ''));
      RETURN NEW;
    END $$;
    """)
    op.execute("""
    CREATE TRIGGER candidates_search_tsvector_sync
    BEFORE INSERT OR UPDATE OF search_text ON candidates
    FOR EACH ROW EXECUTE FUNCTION candidates_search_tsvector_sync();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS candidates_search_tsvector_sync ON candidates")
    op.execute("DROP FUNCTION IF EXISTS candidates_search_tsvector_sync()")
    op.drop_table('resume_files')
    op.drop_index(op.f('ix_candidate_revisions_candidate_id'), table_name='candidate_revisions')
    op.drop_table('candidate_revisions')
    op.drop_index(op.f('ix_candidate_overrides_candidate_id'), table_name='candidate_overrides')
    op.drop_table('candidate_overrides')
    op.drop_index('ix_candidate_embeddings_hnsw', table_name='candidate_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('candidate_embeddings')
    op.drop_index(op.f('ix_parse_runs_workspace_id'), table_name='parse_runs')
    op.drop_index(op.f('ix_parse_runs_status'), table_name='parse_runs')
    op.drop_index(op.f('ix_parse_runs_run_id'), table_name='parse_runs')
    op.drop_table('parse_runs')
    op.drop_index('ix_candidates_workspace_status', table_name='candidates')
    op.drop_index(op.f('ix_candidates_workspace_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index('ix_candidates_search_tsv', table_name='candidates', postgresql_using='gin')
    op.drop_index('ix_candidates_dedup', table_name='candidates', postgresql_where=sa.text("status IN ('active','deleted','pending_review')"))
    op.drop_table('candidates')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('resume_irs')
    op.drop_table('pii_mappings')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS override_action")
    op.execute("DROP TYPE IF EXISTS embedding_segment")
    op.execute("DROP TYPE IF EXISTS failure_class")
    op.execute("DROP TYPE IF EXISTS parse_run_status")
    op.execute("DROP TYPE IF EXISTS candidate_status")
    op.execute("DROP TYPE IF EXISTS pii_type")
