"""conversations support search sessions

Revision ID: 7165970c22da
Revises: a1b2c3d4e5f6
Create Date: 2026-08-08 18:46:12.906030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7165970c22da'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('workspace_id', sa.BigInteger(), nullable=True))
    op.alter_column('conversations', 'knowledge_base_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_conversations_workspace_id_workspaces'), 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_conversations_workspace_id_workspaces'), 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.alter_column('conversations', 'knowledge_base_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('conversations', 'workspace_id')
    # ### end Alembic commands ###
