"""add job tables

Revision ID: bec3fa5d16c7
Revises: 08243aff3b16
Create Date: 2026-08-08 21:24:21.711225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec3fa5d16c7'
down_revision: Union[str, Sequence[str], None] = '08243aff3b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('salary_range', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='job_status'), nullable=False),
    sa.Column('latest_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_index('ix_jobs_workspace_status', 'jobs', ['workspace_id', 'status'], unique=False)
    op.create_table('job_requirement_revisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parsed_ast', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_job_requirement_revisions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_requirement_revisions_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirement_revisions'))
    )
    op.create_index('ix_job_req_rev_job_number', 'job_requirement_revisions', ['job_id', 'revision'], unique=False)
    op.create_index(op.f('ix_job_requirement_revisions_job_id'), 'job_requirement_revisions', ['job_id'], unique=False)
    op.create_table('job_requirement_overrides',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('field_path', sa.String(length=128), nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('action', postgresql.ENUM('override', 'clear', name='override_action', create_type=False), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_job_requirement_overrides_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_requirement_overrides_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['job_requirement_revisions.id'], name=op.f('fk_job_requirement_overrides_revision_id_job_requirement_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirement_overrides'))
    )
    op.create_index(op.f('ix_job_requirement_overrides_job_id'), 'job_requirement_overrides', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_requirement_overrides_job_id'), table_name='job_requirement_overrides')
    op.drop_table('job_requirement_overrides')
    op.drop_index(op.f('ix_job_requirement_revisions_job_id'), table_name='job_requirement_revisions')
    op.drop_index('ix_job_req_rev_job_number', table_name='job_requirement_revisions')
    op.drop_table('job_requirement_revisions')
    op.drop_index('ix_jobs_workspace_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS job_status")
