"""add interview rounds

Revision ID: efe269148628
Revises: 10421097d4d1
Create Date: 2026-08-09 01:06:21.851538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe269148628'
down_revision: Union[str, Sequence[str], None] = '10421097d4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_rounds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('conclusion', sa.Enum('advance', 'recommend', 'reject', 'hold', name='feedback_conclusion'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_history', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_interview_rounds_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_interview_rounds_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], name=op.f('fk_interview_rounds_interviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_interview_rounds_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_rounds'))
    )
    op.create_index(op.f('ix_interview_rounds_assignment_id'), 'interview_rounds', ['assignment_id'], unique=False)
    op.create_index('ix_interview_rounds_assignment_no', 'interview_rounds', ['assignment_id', 'round_no'], unique=False)
    op.create_index(op.f('ix_interview_rounds_workspace_id'), 'interview_rounds', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_rounds_workspace_id'), table_name='interview_rounds')
    op.drop_index('ix_interview_rounds_assignment_no', table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_assignment_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS feedback_conclusion")
