# Generated by Django 5.2.16 on 2026-08-13 12:41

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('current_city', models.CharField(blank=True, default='', max_length=64)),
                ('target_city', models.CharField(blank=True, default='', max_length=64)),
                ('highest_degree', models.CharField(blank=True, default='', max_length=32)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_candidate',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('department', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_job',
            },
        ),
        migrations.CreateModel(
            name='CandidateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING_SCREEN', 'Pending screen'), ('SCREEN_PASSED', 'Screen passed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING_SCREEN', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.job')),
            ],
            options={
                'db_table': 'hr_candidate_assignment',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_SCREEN', 'SCREEN_PASSED'])), fields=('workspace_id', 'candidate', 'job'), name='hr_one_active_assignment_per_candidate_job')],
            },
        ),
    ]
