# Generated by Django 5.2.16 on 2026-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gte', 1)), name='hr_job_headcount_at_least_one'),
        ),
    ]
