# Generated by Django 5.2.16 on 2026-08-13 15:09

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_job_hr_job_headcount_at_least_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.IntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('source_channel', models.CharField(choices=[('REFERRAL', 'Referral'), ('JOB_SITE', 'Job site'), ('HEADHUNTER', 'Headhunter'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.candidate')),
            ],
            options={
                'db_table': 'hr_resume_file',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'sha256'), name='hr_unique_resume_sha256_per_workspace')],
            },
        ),
    ]
