# Generated by Django 5.2.16 on 2026-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_resumefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill_requirements',
            field=models.JSONField(default=list),
        ),
    ]
