# Generated by Django 5.2.16 on 2026-08-13 15:43

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_job_skill_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('round_no', models.PositiveSmallIntegerField()),
                ('interviewer', models.CharField(blank=True, default='', max_length=64)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('feedback', models.TextField(blank=True, default='')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_interview',
            },
        ),
        migrations.RemoveConstraint(
            model_name='candidateassignment',
            name='hr_one_active_assignment_per_candidate_job',
        ),
        migrations.AlterField(
            model_name='candidateassignment',
            name='status',
            field=models.CharField(choices=[('PENDING_SCREEN', 'Pending screen'), ('SCREEN_PASSED', 'Screen passed'), ('INTERVIEWING', 'Interviewing'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING_SCREEN', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='candidateassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_SCREEN', 'SCREEN_PASSED', 'INTERVIEWING', 'OFFER'])), fields=('workspace_id', 'candidate', 'job'), name='hr_one_active_assignment_per_candidate_job'),
        ),
        migrations.AddField(
            model_name='interview',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment'),
        ),
    ]
