# Generated by Django 5.2.16 on 2026-08-13 16:16

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_interview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrConfig',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=64, unique=True)),
                ('llm_model_id', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_config',
            },
        ),
    ]
