# Generated by Django 5.2.16 on 2026-08-14 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_hrconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassignment',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidateassignment',
            name='channel',
            field=models.CharField(choices=[('REFERRAL', 'Referral'), ('JOB_SITE', 'Job site'), ('HEADHUNTER', 'Headhunter'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateassignment',
            name='is_reapply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateassignment',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateassignment',
            name='relation_type',
            field=models.CharField(choices=[('APPLY', 'Apply'), ('SEEK', 'Seek'), ('REFERRAL', 'Referral'), ('HEADHUNTER', 'Headhunter')], default='APPLY', max_length=16),
        ),
        migrations.AddField(
            model_name='candidateassignment',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('NOT_FIT', 'Not fit'), ('SALARY', 'Salary'), ('UNREACHABLE', 'Unreachable'), ('CANDIDATE_WITHDRAW', 'Candidate withdraw'), ('JOB_CLOSED', 'Job closed'), ('MERGED', 'Merged'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('DUPLICATE', 'Duplicate'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateassignment',
            name='status',
            field=models.CharField(choices=[('PENDING_SCREEN', 'Pending screen'), ('SCREEN_PASSED', 'Screen passed'), ('INTERVIEWING', 'Interviewing'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='PENDING_SCREEN', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ON_HOLD', 'On hold'), ('CLOSED', 'Closed')], default='OPEN', max_length=16),
        ),
    ]
