# Generated by Django 5.2.16 on 2026-08-14 06:05

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_candidateassignment_applied_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.UUIDField()),
                ('action', models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access denied')], max_length=32)),
                ('object_type', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('JOB', 'Job'), ('ASSIGNMENT', 'Assignment'), ('RESUME', 'Resume'), ('HR_ACCESS', 'HR access'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied')], default='SUCCESS', max_length=8)),
                ('detail', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'hr_audit_log',
            },
        ),
        migrations.CreateModel(
            name='HrAccess',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('OPERATOR', 'Operator'), ('ADMIN', 'Admin')], default='VIEWER', max_length=16)),
            ],
            options={
                'db_table': 'hr_access',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'user_id'), name='hr_access_unique_workspace_user')],
            },
        ),
    ]
