# Generated by Django 5.2.16 on 2026-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_hrauditlog_hraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='consent_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NOTIFIED', 'Notified'), ('CONSENTED', 'Consented'), ('NOT_REQUIRED', 'Not required')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='contact_preference',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('NO_CONTACT', 'No contact'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_detail',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_type',
            field=models.CharField(choices=[('REFERRAL', 'Referral'), ('JOB_SITE', 'Job site'), ('HEADHUNTER', 'Headhunter'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=16),
        ),
    ]
