# Generated by Django 5.2.16 on 2026-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_candidate_collected_at_candidate_consent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='feedback_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('INTERVIEW_FEEDBACK', 'Interview feedback'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access denied')], max_length=32),
        ),
    ]
