# Generated by Django 5.2.16 on 2026-08-15 06:47

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_interview_feedback_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='handoff_target_type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('WEBHOOK', 'Webhook')], default='CHECKLIST', max_length=16),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='handoff_webhook_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='hrauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('INTERVIEW_FEEDBACK', 'Interview feedback'), ('OFFER_SEND', 'Offer send'), ('OFFER_ACCEPT', 'Offer accept'), ('OFFER_REJECT', 'Offer reject'), ('OFFER_WITHDRAW', 'Offer withdraw'), ('OFFER_APPROVE', 'Offer approve'), ('HANDOFF', 'Handoff'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access denied')], max_length=32),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=16)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='CNY', max_length=16)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_path', models.CharField(blank=True, default='', max_length=1024)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
            ],
            options={
                'db_table': 'hr_offer',
            },
        ),
        migrations.CreateModel(
            name='OnboardingHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('payload', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('handoff_time', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.offer')),
            ],
            options={
                'db_table': 'hr_onboarding_handoff',
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'assignment', 'version'), name='hr_unique_offer_version_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoff',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'assignment'), name='hr_unique_handoff_per_assignment'),
        ),
    ]
