# Generated by Django 5.2.16 on 2026-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_hrconfig_handoff_target_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('INTERVIEW_FEEDBACK', 'Interview feedback'), ('OFFER_SEND', 'Offer send'), ('OFFER_ACCEPT', 'Offer accept'), ('OFFER_REJECT', 'Offer reject'), ('OFFER_WITHDRAW', 'Offer withdraw'), ('OFFER_APPROVE', 'Offer approve'), ('HANDOFF', 'Handoff'), ('IMPORT', 'Import'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access denied')], max_length=32),
        ),
    ]
