# Generated by Django 5.2.16 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_hrauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='document_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='语义索引文档id'),
        ),
    ]
