# Generated by Django 5.2.16 on 2026-08-15

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_resumefile_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFlowLog',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('resume_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('candidate_id', models.UUIDField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('node', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(default='SUCCESS', max_length=16)),
                ('detail', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_resume_flow_log',
                'indexes': [models.Index(fields=['workspace_id', 'resume_id', 'create_time'], name='hr_flow_log_ws_resume_time_idx')],
            },
        ),
    ]
