# Generated by Django 5.2.16 on 2026-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_resumeflowlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumeflowlog',
            new_name='hr_resume_flow_ws_rs_time_idx',
            old_name='hr_flow_log_ws_resume_time_idx',
        ),
    ]
