# Generated by Django 5.2.16 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_rename_hr_flow_log_ws_resume_time_idx_hr_resume_flow_ws_rs_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='rerank_model_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='重排序模型id'),
        ),
    ]
