# Generated by Django 5.2.16 on 2026-08-15 16:34
# 注意：文件名为自动生成时的瞬态状态残留（曾移除后重加 rerank_model_id），实际内容仅为
# HrAuditLog.action 增加 SEARCH 选项；rerank_model_id 字段仍保留（0016 添加）。
# 不改文件名：已应用迁移按 django_migrations 记录名匹配，改名会导致漂移。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_hrconfig_rerank_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('INTERVIEW_FEEDBACK', 'Interview feedback'), ('OFFER_SEND', 'Offer send'), ('OFFER_ACCEPT', 'Offer accept'), ('OFFER_REJECT', 'Offer reject'), ('OFFER_WITHDRAW', 'Offer withdraw'), ('OFFER_APPROVE', 'Offer approve'), ('HANDOFF', 'Handoff'), ('IMPORT', 'Import'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('SEARCH', 'Resume semantic search'), ('ACCESS_DENIED', 'Access denied')], max_length=32),
        ),
    ]
