# Generated by Django 5.2.16 on 2026-08-16 05:53

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_remove_hrconfig_rerank_model_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('skill_norm', models.CharField(db_index=True, max_length=128)),
                ('skill_raw', models.CharField(max_length=128)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rows', to='hr.candidate')),
            ],
            options={
                'db_table': 'hr_candidate_skill',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'skill_norm'), name='hr_candidate_skill_uniq')],
            },
        ),
    ]
