# Generated by Django 5.2.16 on 2026-08-16 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_candidateskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('relation_type', models.CharField(choices=[('APPLY', 'Apply'), ('SEEK', 'Seek'), ('REFERRAL', 'Referral'), ('HEADHUNTER', 'Headhunter')], default='APPLY', max_length=16)),
                ('channel', models.CharField(choices=[('REFERRAL', 'Referral'), ('JOB_SITE', 'Job site'), ('HEADHUNTER', 'Headhunter'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('channel_detail', models.CharField(blank=True, default='', max_length=128)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('recruiter_id', models.UUIDField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('NOT_FIT', 'Not fit'), ('SALARY', 'Salary'), ('UNREACHABLE', 'Unreachable'), ('CANDIDATE_WITHDRAW', 'Candidate withdraw'), ('JOB_CLOSED', 'Job closed'), ('MERGED', 'Merged'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('reapply_no', models.PositiveSmallIntegerField(default=0)),
                ('rehire_confirmed', models.BooleanField(default=False)),
                ('rehire_reason', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.job')),
                ('reapply_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.application')),
            ],
            options={
                'db_table': 'hr_application',
            },
        ),
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_system', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='hr.job')),
            ],
            options={
                'db_table': 'hr_job_stage',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STAGE_MOVED', 'Stage moved'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed'), ('RESTORED', 'Restored')], max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(blank=True, default='', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.application')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.jobstage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.jobstage')),
            ],
            options={
                'db_table': 'hr_application_event',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.jobstage'),
        ),
        migrations.AddConstraint(
            model_name='jobstage',
            constraint=models.UniqueConstraint(fields=('job', 'order'), name='hr_job_stage_job_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='jobstage',
            constraint=models.UniqueConstraint(fields=('job', 'key'), name='hr_job_stage_job_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='jobstage',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='hr_job_stage_job_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='applicationevent',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'application', 'event_type', 'idempotency_key'), name='hr_application_event_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('workspace_id', 'candidate', 'job'), name='hr_application_one_active_per_candidate_job'),
        ),
    ]
