# Generated by Django 5.2.16 on 2026-08-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_application_jobstage_applicationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.application'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hr.application'),
        ),
        migrations.AddField(
            model_name='onboardinghandoff',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='hr.application'),
        ),
        migrations.AlterField(
            model_name='hrauditlog',
            name='object_type',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('JOB', 'Job'), ('ASSIGNMENT', 'Assignment'), ('APPLICATION', 'Application'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ONBOARDING', 'Onboarding'), ('RESUME', 'Resume'), ('HR_ACCESS', 'HR access'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='interview',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment'),
        ),
        migrations.AlterField(
            model_name='onboardinghandoff',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.candidateassignment'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'application', 'round_no'), name='hr_unique_interview_round_per_application'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'application', 'version'), name='hr_unique_offer_version_per_application'),
        ),
        migrations.AddConstraint(
            model_name='onboardinghandoff',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'application'), name='hr_unique_handoff_per_application'),
        ),
    ]
