# Generated by Django 5.2.16 on 2026-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_interview_application_offer_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IMPORTED', 'Imported'), ('STAGE_MOVED', 'Stage moved'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed'), ('RESTORED', 'Restored')], max_length=32),
        ),
    ]
