# Generated by Django 5.2.16 on 2026-08-16 17:36

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_applicationevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrauditlog',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_enable_screening',
            field=models.BooleanField(default=False, verbose_name='Screening Agent 开关'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_max_concurrent_runs',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Agent 并发运行上限'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_run_rate_limit',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Agent 每小时触发上限'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_score_bands',
            field=models.JSONField(default=dict, verbose_name='评分分带（advance/hold）'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_score_version',
            field=models.CharField(default='v1', max_length=32, verbose_name='评分函数版本'),
        ),
        migrations.AlterField(
            model_name='hrauditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_DETAIL', 'View detail'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('DELETE', 'Delete'), ('JOB_CLOSE', 'Job close'), ('JOB_REOPEN', 'Job reopen'), ('ASSIGNMENT_TRANSITION', 'Assignment transition'), ('RESUME_UPLOAD', 'Resume upload'), ('RESUME_DOWNLOAD', 'Resume download'), ('RESUME_DELETE', 'Resume delete'), ('INTERVIEW_FEEDBACK', 'Interview feedback'), ('OFFER_SEND', 'Offer send'), ('OFFER_ACCEPT', 'Offer accept'), ('OFFER_REJECT', 'Offer reject'), ('OFFER_WITHDRAW', 'Offer withdraw'), ('OFFER_APPROVE', 'Offer approve'), ('HANDOFF', 'Handoff'), ('IMPORT', 'Import'), ('MERGE', 'Merge'), ('GRANT_ACCESS', 'Grant access'), ('REVOKE_ACCESS', 'Revoke access'), ('EXPORT', 'Export'), ('SEARCH', 'Resume semantic search'), ('AGENT_RUN', 'Agent run'), ('AGENT_DECIDE', 'Agent decide'), ('ACCESS_DENIED', 'Access denied')], max_length=32),
        ),
        migrations.CreateModel(
            name='HrAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('agent_type', models.CharField(choices=[('SCREENING', 'Screening')], default='SCREENING', max_length=16)),
                ('trigger_type', models.CharField(choices=[('EVENT', 'Event'), ('MANUAL', 'Manual')], default='EVENT', max_length=16)),
                ('ref_object_type', models.CharField(default='APPLICATION', max_length=32)),
                ('ref_object_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('input_meta', models.JSONField(default=dict)),
                ('tool_trace', models.JSONField(default=list)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('llm_model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('duration_ms', models.IntegerField(default=0)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_agent_run',
                'indexes': [models.Index(fields=['workspace_id', 'agent_type', 'status'], name='hr_agent_run_ws_type_status'), models.Index(fields=['workspace_id', 'ref_object_id'], name='hr_agent_run_ws_ref_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrAgentProposal',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(default='APPLICATION', max_length=32)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('ADVANCE', 'Advance'), ('DECLINE', 'Decline'), ('HOLD', 'Hold'), ('DRAFT', 'Draft')], max_length=16)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='hr.hragentrun')),
            ],
            options={
                'db_table': 'hr_agent_proposal',
                'indexes': [models.Index(fields=['workspace_id', 'target_type', 'target_id', 'status'], name='hr_agent_proposal_ws_target_st')],
            },
        ),
    ]
