# Generated by Django 5.2.16 on 2026-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_hrauditlog_trace_id_hrconfig_agent_enable_screening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='agent_knowledge_bases',
            field=models.JSONField(default=list, verbose_name='Agent 可用企业知识库白名单（id 列表）'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='agent_prompt_versions',
            field=models.JSONField(default=dict, verbose_name='Agent 提示词生效版本（只读）'),
        ),
        migrations.AlterField(
            model_name='hragentrun',
            name='agent_type',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('JD_DRAFT', 'JD Draft'), ('INTERVIEW_COPILOT', 'Interview Copilot')], default='SCREENING', max_length=32),
        ),
    ]
