# Generated by Django 5.2.16 on 2026-08-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_hrconfig_agent_knowledge_bases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hragentrun',
            name='agent_type',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('JD_DRAFT', 'JD Draft'), ('INTERVIEW_COPILOT', 'Interview Copilot'), ('SOURCING', 'Sourcing'), ('COMMUNICATION_DRAFT', 'Communication Draft')], default='SCREENING', max_length=32),
        ),
    ]
