# Generated by Django 5.2.16 on 2026-08-17 09:04
#
# 0025：删除 Legacy CandidateAssignment，并把存量指派对接到 Application（ATS v2）。
# 修订：在删表前加 RunPython 数据兜底，避免线上存量 hr_candidate_assignment 直接丢失：
#   1) 为没有 Pipeline 的 Job 创建默认 JobStage；
#   2) CandidateAssignment → Application（PENDING_SCREEN→APPLIED/ACTIVE、SCREEN_PASSED→SCREEN/ACTIVE、
#      INTERVIEWING→INTERVIEW/ACTIVE、OFFER→OFFER/ACTIVE、HIRED/REJECTED/WITHDRAWN/CLOSED→对应终态）；
#   3) 每条存量指派写一条 ApplicationEvent(IMPORTED, idempotency_key="import:{assignment_id}") 幂等锚点
#      （同 (event_type, idempotency_key) 已存在即跳过，迁移本身只跑一次）；
#   4) 把 Interview / Offer / Handoff 的 assignment_id 回填为新的 application_id；
#   5) 最后再删除约束 / 字段 / 表。
from django.db import migrations, transaction

_DEFAULT_STAGES = [
    ("APPLIED", "待筛选", 1),
    ("SCREEN", "初筛", 2),
    ("INTERVIEW", "面试", 3),
    ("OFFER", "Offer", 4),
]

# 旧指派状态 → (新阶段 key, 新 status)；终态 stage_key 为 None（落到最后一个阶段）
_STATUS_MAP = {
    "PENDING_SCREEN": ("APPLIED", "ACTIVE"),
    "SCREEN_PASSED": ("SCREEN", "ACTIVE"),
    "INTERVIEWING": ("INTERVIEW", "ACTIVE"),
    "OFFER": ("OFFER", "ACTIVE"),
    "HIRED": (None, "HIRED"),
    "REJECTED": (None, "REJECTED"),
    "WITHDRAWN": (None, "WITHDRAWN"),
    "CLOSED": (None, "CLOSED"),
}
_TERMINAL = {"HIRED", "REJECTED", "WITHDRAWN", "CLOSED"}
# 终态默认终止原因（旧表无原因时兜底，不丢语义）
_DEFAULT_REASON = {
    "REJECTED": "OTHER",
    "WITHDRAWN": "OTHER",
    "CLOSED": "JOB_CLOSED",
}


def _create_default_stages(apps, job):
    JobStage = apps.get_model("hr", "JobStage")
    JobStage.objects.bulk_create(
        [
            JobStage(
                workspace_id=job.workspace_id,
                job=job,
                key=key,
                name=name,
                order=order,
                is_system=True,
            )
            for key, name, order in _DEFAULT_STAGES
        ]
    )


def backfill_legacy_assignments(apps, schema_editor):
    CandidateAssignment = apps.get_model("hr", "CandidateAssignment")
    Application = apps.get_model("hr", "Application")
    ApplicationEvent = apps.get_model("hr", "ApplicationEvent")
    Job = apps.get_model("hr", "Job")
    JobStage = apps.get_model("hr", "JobStage")
    Interview = apps.get_model("hr", "Interview")
    Offer = apps.get_model("hr", "Offer")
    OnboardingHandoff = apps.get_model("hr", "OnboardingHandoff")

    # 1) 为没有 Pipeline 的 Job 创建默认 JobStage
    stages_created = 0
    for job in Job.objects.all().order_by("create_time"):
        if not JobStage.objects.filter(job=job).exists():
            _create_default_stages(apps, job)
            stages_created += 1

    mapping = {}
    prev_by_key = {}
    imported = skipped = 0

    assignments = CandidateAssignment.objects.all().select_related("candidate", "job").order_by("create_time")
    for assignment in assignments:
        marker = f"import:{assignment.id}"
        # 幂等锚点：同 (event_type, idempotency_key) 已存在视为已导入
        if ApplicationEvent.objects.filter(event_type="IMPORTED", idempotency_key=marker).exists():
            existing = (
                Application.objects.filter(
                    workspace_id=assignment.workspace_id,
                    candidate_id=assignment.candidate_id,
                    job_id=assignment.job_id,
                )
                .order_by("create_time")
                .first()
            )
            if existing is not None:
                mapping[str(assignment.id)] = existing
            skipped += 1
            continue

        stage_key, status = _STATUS_MAP.get(assignment.status, (None, "ACTIVE"))
        stages = list(JobStage.objects.filter(job=assignment.job).order_by("order"))
        if not stages:
            skipped += 1
            continue
        if stage_key is None:
            stage = stages[-1]
        else:
            stage = next((s for s in stages if s.key == stage_key), stages[0])
        terminal = status in _TERMINAL
        key = (assignment.workspace_id, str(assignment.candidate_id), str(assignment.job_id))
        previous = prev_by_key.get(key)
        reapply_no = (previous.reapply_no if previous else 0) + 1
        terminated_at = assignment.update_time if terminal else None
        termination_reason = (
            assignment.termination_reason
            if terminal and assignment.termination_reason
            else (_DEFAULT_REASON.get(status) if terminal else None)
        )
        with transaction.atomic():
            application = Application.objects.create(
                workspace_id=assignment.workspace_id,
                user_id=assignment.user_id,
                candidate_id=assignment.candidate_id,
                job_id=assignment.job_id,
                current_stage=stage,
                status=status,
                relation_type=assignment.relation_type,
                channel=assignment.channel,
                applied_at=assignment.applied_at,
                owner_id=assignment.owner_id,
                recruiter_id=assignment.owner_id,
                termination_reason=termination_reason,
                terminated_at=terminated_at,
                reapply_of=previous,
                reapply_no=reapply_no,
                note=assignment.note,
            )
            ApplicationEvent.objects.create(
                workspace_id=assignment.workspace_id,
                application=application,
                event_type="IMPORTED",
                from_stage=None,
                to_stage=stage,
                from_status="",
                to_status=status,
                actor_id=None,
                reason_code=assignment.status,
                reason_text=f"migrated from CandidateAssignment {assignment.id}",
                idempotency_key=marker,
                trace_id="",
            )
        prev_by_key[key] = application
        mapping[str(assignment.id)] = application
        imported += 1

    # 2) 回填 Interview / Offer / Handoff 的 application_id
    linked = 0
    if mapping:
        for model in (Interview, Offer, OnboardingHandoff):
            rows = model.objects.filter(
                assignment_id__in=list(mapping.keys()), application_id__isnull=True
            )
            for row in rows:
                app = mapping.get(str(row.assignment_id))
                if app is None:
                    continue
                row.application_id = app.id
                row.save(update_fields=["application_id"])
                linked += 1

    # 本 schema 外键均为 DEFERRABLE INITIALLY DEFERRED：回填 UPDATE/INSERT 会在本事务排队
    # 延迟外键校验事件，导致后续 ALTER TABLE DROP CONSTRAINT 报
    # "cannot ALTER TABLE ... pending trigger events"。这里立即校验并清空待处理事件，
    # 同时作为一次性完整性断言（任一回填引用不成立会在此抛 FK 违规并回滚整表）。
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")

    print(
        f"[0025] legacy assignment backfill: imported={imported} skipped={skipped} "
        f"stages_created={stages_created} linked_sub_objects={linked}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0024_alter_hragentrun_agent_type"),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_assignments, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="offer",
            name="hr_unique_offer_version_per_assignment",
        ),
        migrations.RemoveConstraint(
            model_name="onboardinghandoff",
            name="hr_unique_handoff_per_assignment",
        ),
        migrations.RemoveField(
            model_name="onboardinghandoff",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="CandidateAssignment",
        ),
    ]
