# Generated by Django 5.2

import uuid_utils.compat
from django.db import migrations, models
import django.db.models.deletion


def backfill_default_databases(apps, schema_editor):
    ResumeDatabase = apps.get_model("hr", "ResumeDatabase")
    ResumeFile = apps.get_model("hr", "ResumeFile")
    workspace_ids = ResumeFile.objects.values_list("workspace_id", flat=True).distinct()
    for workspace_id in workspace_ids:
        database, _ = ResumeDatabase.objects.get_or_create(
            workspace_id=workspace_id,
            name="默认简历库",
            defaults={"is_default": True, "status": "ACTIVE"},
        )
        ResumeFile.objects.filter(workspace_id=workspace_id, resume_database__isnull=True).update(resume_database=database)


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0026_hroffboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeDatabase",
            fields=[
                ("id", models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, default="", max_length=512)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")], default="ACTIVE", max_length=16)),
                ("is_default", models.BooleanField(default=False)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "hr_resume_database"},
        ),
        migrations.AddField(
            model_name="resumefile",
            name="resume_database",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resume_files", to="hr.resumedatabase"),
        ),
        migrations.AddConstraint(
            model_name="resumedatabase",
            constraint=models.UniqueConstraint(fields=("workspace_id", "name"), name="hr_resume_database_workspace_name_uniq"),
        ),
        migrations.RunPython(backfill_default_databases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="resumefile",
            name="resume_database",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resume_files", to="hr.resumedatabase"),
        ),
    ]
