# Generated by Django 5.2

import uuid_utils.compat
from django.db import migrations, models
import django.db.models.deletion


def backfill_total_memberships(apps, schema_editor):
    ResumeDatabase = apps.get_model("hr", "ResumeDatabase")
    ResumeFile = apps.get_model("hr", "ResumeFile")
    Membership = apps.get_model("hr", "ResumeDatabaseMembership")

    workspace_ids = ResumeFile.objects.values_list("workspace_id", flat=True).distinct()
    for workspace_id in workspace_ids:
        total = ResumeDatabase.objects.filter(workspace_id=workspace_id, is_default=True).first()
        if total is None:
            total = ResumeDatabase.objects.create(
                workspace_id=workspace_id,
                name="总库",
                is_default=True,
                is_system=True,
                status="ACTIVE",
            )
        else:
            total.is_system = True
            if total.name == "默认简历库":
                total.name = "总库"
            total.save(update_fields=["is_system", "name", "update_time"])

        for resume in ResumeFile.objects.filter(workspace_id=workspace_id).only("id", "resume_database_id"):
            Membership.objects.get_or_create(resume_file_id=resume.id, resume_database_id=total.id)
            if resume.resume_database_id:
                Membership.objects.get_or_create(
                    resume_file_id=resume.id, resume_database_id=resume.resume_database_id
                )


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0027_resumedatabase"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedatabase",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ResumeDatabaseMembership",
            fields=[
                ("id", models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("resume_database", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resume_memberships", to="hr.resumedatabase")),
                ("resume_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="database_memberships", to="hr.resumefile")),
            ],
            options={"db_table": "hr_resume_database_membership"},
        ),
        migrations.AddConstraint(
            model_name="resumedatabasemembership",
            constraint=models.UniqueConstraint(fields=("resume_file", "resume_database"), name="hr_resume_database_membership_uniq"),
        ),
        migrations.RunPython(backfill_total_memberships, migrations.RunPython.noop),
    ]
