# Generated by Django 5.2.16 on 2026-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_resumedatabasemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='raw_text',
            field=models.TextField(blank=True, default='', verbose_name='docx/txt 提取原文（混合检索关键字腿）'),
        ),
    ]
