from django.urls import path

from hr import views

app_name = "hr"

urlpatterns = [
    path("workspace/<str:workspace_id>/hr/candidates", views.CandidateAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/resumes", views.ResumeAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<int:current_page>/<int:page_size>", views.CandidateAPI.Page.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/check-duplicate", views.CandidateCheckDuplicateAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>", views.CandidateDetailAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>/archive", views.CandidateDetailAPI.Archive.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>/restore", views.CandidateDetailAPI.Restore.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>/delete", views.CandidateDetailAPI.Delete.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>/merge", views.CandidateDetailAPI.Merge.as_view()),
    path("workspace/<str:workspace_id>/hr/candidates/<str:candidate_id>/resumes", views.ResumeListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/export/candidates", views.CandidateExportAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs", views.JobAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<int:current_page>/<int:page_size>", views.JobAPI.Page.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>", views.JobDetailAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/close-preview", views.JobClosePreviewAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/close", views.JobCloseAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/reopen", views.JobDetailAPI.Reopen.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/assignments", views.JobAPI.Assignment.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/matches/<int:current_page>/<int:page_size>", views.JobMatchAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/assignments/<str:assignment_id>", views.AssignmentAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/assignments/<str:assignment_id>/interviews", views.InterviewAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/assignments/<str:assignment_id>/offers", views.OfferListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/page/<int:current_page>/<int:page_size>", views.AllOffersAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>", views.OfferDetailAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/approve", views.OfferDetailAPI.Approve.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/send", views.OfferDetailAPI.Send.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/accept", views.OfferDetailAPI.Accept.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/reject", views.OfferDetailAPI.Reject.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/withdraw", views.OfferDetailAPI.Withdraw.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/attachment", views.OfferDetailAPI.Attachment.as_view()),
    path("workspace/<str:workspace_id>/hr/offers/<str:offer_id>/attachment/download", views.OfferDetailAPI.Attachment.Download.as_view()),
    path("workspace/<str:workspace_id>/hr/handoffs/<int:current_page>/<int:page_size>", views.HandoffListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/handoffs/<str:handoff_id>/retry", views.HandoffRetryAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/handoff/config", views.HandoffConfigAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/interviews/mine", views.InterviewerMineAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/interviews/<str:interview_id>/feedback", views.InterviewerFeedbackAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/interviews/<str:interview_id>", views.InterviewDetailAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/batch-status", views.ResumeBatchStatusAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/search", views.HrResumeSearchAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/<str:resume_id>", views.ResumeDetailAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/<str:resume_id>/download", views.ResumeDetailAPI.Download.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/<str:resume_id>/content", views.ResumeDetailAPI.Content.as_view()),
    path("workspace/<str:workspace_id>/hr/resumes/<str:resume_id>/flow-logs", views.ResumeFlowLogAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/ai/config", views.HrAIConfigAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/ai/search-parse", views.HrSearchParseAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/ai/extract-skills", views.HrSkillExtractAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/import/candidates/template", views.CandidateImportTemplateAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/import/candidates", views.CandidateImportAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/access", views.HrAccessAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/access/me", views.HrAccessMeAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/jobs/<str:job_id>/stages", views.JobStageListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications", views.ApplicationListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/page/<int:current_page>/<int:page_size>", views.ApplicationPageAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/move-stage", views.ApplicationMoveStageAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/terminal", views.ApplicationTerminalAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/restore", views.ApplicationRestoreAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/events", views.ApplicationEventAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/interviews", views.ApplicationInterviewAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/applications/<str:application_id>/offers", views.ApplicationOfferListAPI.as_view()),
    path("workspace/<str:workspace_id>/hr/audit-logs", views.HrAuditLogAPI.as_view()),
]
